#!/usr/bin/env bash

# check for wifi adapters plugged in
if [ -f "/home/pi/sisbot-server/sisbot/wifi_adapter_check.sh" ]; then
  /home/pi/sisbot-server/sisbot/wifi_adapter_check.sh
fi

#check for node_modules in each folder
cd /home/pi/sisbot-server/sisbot
if [ -d "node_modules" ] then
  echo "Sisbot node_modules found"
else
  sudo -u pi npm install
fi
cd /home/pi/sisbot-server/siscloud
if [ -d "node_modules" ] then
  echo "Siscloud node_modules found"
else
  sudo -u pi npm install
fi
cd /home/pi/sisbot-server/sisproxy && git reset --hard
if [ -d "node_modules" ] then
  echo "Sisproxy node_modules found"
else
  sudo -u pi npm install
fi

start_time="$(date -u +%s)"

{
  sudo NODE_ENV=sisbot node server.js >> /var/log/sisyphus/proxy.log  2>&1
} || {
  end_time="$(date -u +%s)"
  elapsed="$(($end_time-$start_time))"
  echo "Test failure"
  echo "$elapsed"
  if [ $elapsed -lt 3 ]; then
    echo "Proxy crashed"

    echo "Make sure we are connected to internet"
    RETRIES=0
    FAILED=false
    while ! ping -c 1 -W 2 google.com ; do
      sleep 1
  		RETRIES=RETRIES+1
      if [ "$RETRIES" > "25" ] ; then
      	FAILED=true
      fi
    done

    if [ "$FAILED" = false ] ; then
      echo "Failure! Unable to connect to network, please retry."
      return 1
    else
      sudo -u pi npm install
      sleep 5
      ./restart.sh &
    fi
  else
    echo "Normal stop"
  fi
}
